model:
  choice: torchvision-mobilenet_v2 # torchvision- or custom-
  kwargs: {}
  num_classes: 7 # out_channels of fc, maybe be not equal to num_classes of train_dir. 
  pretrained: True
  backbone_freeze: False
  bn_freeze: False
  bn_freeze_affine: False
data:
  root: ./data # -train -val
  nw: 8 # if not multi-nw, set to 0
  imgsz: [[720,720], [224,224]] # [h,w] / [s,s] / [s,]->[adaptive, s] or [s, adaptive]
  train:
    bs: 256 # all gpus if DDP
    augment: # refer to utils/augment.py, !Attention: center&resize is exclusive!
      random_color_jitter
      random_horizonflip
      centercrop_resize
      to_tensor_without_div
      normalize # default use ImageNet1K mean & var, if not pretrained, del normalize
    aug_epoch: 40 # augment for epochs, on which epoch to weaken, except warm_epoch
  val:
    bs: 64
    augment:
      centercrop_resize
      to_tensor_without_div
      normalize
hyp:
  epochs: 50
  lr0: 0.001 # sgd=1e-2, adam=1e-3
  lrf_ratio: None # decay to lrf_ratio * lr0, if None, 0.1
  momentum: 0.937
  weight_decay: 0.0005
  warmup_momentum: 0.8
  warm_ep: 1 # out of epochs, imp linear
  loss:
    ce: True
    bce: False
  label_smooth: 0.1
  strategy:
    prog_learn: True # progressive learning, will effect on mixup and imgsz, devide epoch into 3 parts in default, mixup alpha 0 -> 0.1 -> 0.2, imgsz 0.5 -> ? -> 1
    mixup: 1 [5,25] # ratio and [start, end), on which epoch to start or delete mixup, support ce and bce, default alpha=0.1
    focal: False 0 # turn-on-or-off and start_epo (except warm_epoch)
  optimizer: sgd # sgd or adam
  scheduler: cosine_with_warm # linear or cosine
